image: continuumio/miniconda3

pipelines:
  default:
    - step:
        caches:
          - pip
          - conda
        script: 
          - conda install conda-build anaconda-client
          - cd conda.recipe
          - anaconda login --username $ANACONDA_USER --password $ANACONDA_PASSWORD
          - conda build -c conda-forge -c cmutel -c haasad . 

