image: continuumio/miniconda3:4.7.10

pipelines:
  branches:
          master:
            - step:
                script: 
                  - conda install -y -q --freeze-installed conda-build anaconda-client
                  - cd conda.recipe
                  - anaconda login --username $ANACONDA_USER --password $ANACONDA_PASSWORD
                  - conda config --set anaconda_upload yes
                  - conda build -c conda-forge -c cmutel -c haasad . 
                deployment: production

