# The regex used is a bit different from original documenation:
# https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html#loading-data-from-other-files
# Originald documentation implies that the __init__.py only has one line with __version__
{% set version_match = load_file_regex(load_file="bw2ui/__init__.py", 
regex_pattern='(?:.*)__version__ = "(.+)"') %}
{% set version = version_match[1] %}


package:
        name: bw25ui
        version: {{ version }}

source:
        git_url: ../

requirements:
        build:
                - python
                - setuptools
        run:
                - python >=3.6
                - brightway25
                - bw2calc >=2.0.dev10
                - bw2analyzer >=0.11
                - docopt
                - eight
                - flask
                - jinja2
                - stats_arrays
                - tabulate
                - genson

about:
        home: https://github.com/brightway-lca/brightway2-ui
        license: BSD
        license_file: LICENSE

build:
        entry_points:
                - bw2-browser = bw2ui.bin.bw2_browser:main
                - bw2-web     = bw2ui.bin.bw2_web:main

        noarch: python
        script: {{ PYTHON }} -m pip install --no-deps --no-build-isolation . -vv
