{% set data = load_setup_py_data() %}
package:
        name: bw25ui
        version: {{ data.get('version') }}

requirements:
        build:
                - python
                - setuptools
                - setuptools_scm
        run:
                - python >=3.6
                - brightway25
                - bw2calc >=2.0.dev10
                - bw2analyzer >=0.11
                - docopt
                - eight
                - flask
                - jinja2
                - stats_arrays
                - tabulate
                - genson

about:
        home: https://github.com/brightway-lca/brightway2-ui
        license: BSD
        license_file: LICENSE

build:
        entry_points:
                - bw2-browser = bw2ui.bin.bw2_browser:main
                - bw2-web     = bw2ui.bin.bw2_web:main

        noarch: python
