{% set data = load_setup_py_data() %}
package:
        name: bw2ui
        version: {{ data.get('version') }}

source:
        git_url: ../

requirements:
        build:
                - python
                - setuptools
        run:
                - python >=3.6
                - brightway2
                - bw2calc <2
                - bw2analyzer >=0.10
                - docopt
                - eight
                - flask
                - jinja2
                - stats_arrays
                - tabulate
                - genson

about:
        home: https://github.com/brightway-lca/brightway2-ui
        license: BSD
        license_file: LICENSE

build:
        entry_points:
                - bw2-browser = bw2ui.bin.bw2_browser:main
                - bw2-web     = bw2ui.bin.bw2_web:main

        noarch: python
        script: {{ PYTHON }} -m pip install --no-deps --no-build-isolation . -vv
